### PR TITLE
[Connections] Use relaxed dependency

### PR DESCRIPTION
**Pull request by expobrain**

### CODE REVIEW

**Comment by foxyblue** [comment]
@expobrain What are the benefits of relaxing the dependencies?

**Comment by foxyblue** [comment]
I think pyexasol added a new exception in a later version.

**Comment by expobrain** [comment]
This is a library and it should work with a range of dependencies to leave more flexibility to the final user or to avoid dependency clashes with other libraries

**Comment by expobrain** [comment]
@foxyblue do you happen to remember which exception has been added?

**Comment by foxyblue** [comment]
Here we are checking that ExaCommunicationError occurs when we provide a bad dsn.

```python
    @patch.dict("os.environ", TEST_EVIRONMENT)
    def test_bad_dsn_exasol():
        """ Test passing exasol a bad dsn."""
        with pytest.raises(pyexasol.exceptions.ExaCommunicationError):
>           with get("exasol_bad_dsn"):
```

Pyexasol is correctly raising `ExaConnectionDsnError` <- which was added in `0.6.0`

```python
        try:
            hostname, aliaslist, ipaddrlist = socket.gethostbyname_ex(host)
        except OSError:
>           raise ExaConnectionDsnError(self, f'Could not resolve IP address of host [{host}] '
                                              f'derived from connection string')
```

**Comment by expobrain** [comment]
@foxyblue tho options:

1. in the test you choose the correct exception base on the version of `pyexasol`
2. you have two tests with different exceptions using [skipIf](https://docs.pytest.org/en/latest/skipping.html#id1) to run the correct test for the `pyexasol` lib version
3. you support only `pyexasol>=0.6` and make a bump in the `connections` lib

For option 1 and 2 in Travis you need to add a matrix to execute the `connections` tests with two versions of `pyexasol`.

**Comment by foxyblue** [comment]
I have a preference for your option 3.

I would like to introduce the same change I made in the logger here where you are not relying on the dependencies you don't use.

I like skipif. But I would like to only consider this complexity on Major version changes `0.0.0` -> `1.0.0`.

>For option 1 and 2 in Travis you need to add a matrix to execute the connections tests with two versions of pyexasol.

Same on this point.

**Comment by expobrain** [comment]
Replaced by #36

**Pull request closed without merging**
