### PR TITLE
[Connections] Use revlibs logging

### PR DESCRIPTION
**Pull request by expobrain**

### CODE REVIEW

**Comment by foxyblue** [comment]
The Logging library respects previously created loggers.
```
import logging

logging.info("This")
```
Will use revlibs.logger if it's been initiated by the application.

Also I think importing revlibs.logger again breaks the logger 🤔

**Comment by expobrain** [comment]
I'm expecting `revlibs-logger` to work like the `logging` library, you can set once and call it multiple time.

If not, there's a bug in `revlibs-logger`.

**Comment by expobrain** [comment]
@foxyblue so what we should do with this PR?

**Comment by foxyblue** [comment]
This should be closed, the logger doesn't need to be imported into other libraries.

`modules/subscriber.py:`

```python
import logging

def listen():
    logging.info("Subscriber listening..")
```

`intiate_app.py`

```python
from revlibs.logger import get_logger
from module import subscriber

logging = get_logger()

logging.info("Set logger")
subscriber.listen()
```

#### Output

```bash
(pubsubs) sebastien-macOS pubsubs (enh/kafka-interface)$ python snippet2.py
[2019-04-30 13:01:15,693] INF snippet2.py:6: Set logger
[2019-04-30 13:01:15,704] INF /Users/modules/subscriber.py:23: Subscriber listening..
```

**Pull request closed without merging**
